import type { CompletedSession } from "../sessions/sessions.api";

export const cardTestNight: CompletedSession = {
  session_id: "private-session-id",
  group_id: "private-group-id",
  group_name: "Match Club",
  status: "completed",
  created_at: "2026-07-20T20:00:00Z",
  started_at: "2026-07-20T20:01:00Z",
  winner_selected_at: "2026-07-20T20:08:00Z",
  completed_at: "2026-07-20T20:09:00Z",
  criteria: { mood_cues: ["easygoing"] },
  winner_candidate_id: "winner-id",
  decision_duration_seconds: 420,
  winner_unanimous: false,
  had_tie: false,
  tie_resolution: null,
  watched_status: "watched",
  watched_confirmed_at: null,
  teleparty_was_shared: true,
  teleparty_shared_at: "2026-07-20T20:10:00Z",
  teleparty_handoff_at: null,
  participants: [
    {
      id: "participant-id",
      user_id: "private-user-id",
      display_name: "Private Participant",
      avatar_url: "https://private.example/avatar.png",
      avatar_source: "provider",
      avatar_style: null,
      avatar_seed: null,
      joined_at: null,
      submitted_votes: true,
      role: "host",
      participation_status: "participated",
      criteria: null,
    },
  ],
  candidates: [
    {
      id: "winner-id",
      source_title_id: "title-id",
      source: "tmdb",
      source_id: "1",
      media_type: "movie",
      title: "A Beautiful Film",
      release_year: 2026,
      poster_path: "/poster.jpg",
      backdrop_path: "/backdrop.jpg",
      runtime_minutes: 104,
      genres: ["Drama"],
      overview: "Private overview",
      position: 0,
      yes_count: 1,
      no_count: 0,
      total_vote_count: 1,
      is_winner: true,
      is_finalist: true,
    },
  ],
};
